version: '3.6'

services:

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../:/var/www/instructions
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    restart: unless-stopped
    ports:
      - "8090:80"


  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../:/var/www/instructions
    container_name: ${COMPOSE_PROJECT_NAME}-fpm
    environment:
          XDEBUG_CONFIG: "remote_host=host.docker.internal remote_port=9001 remote_enable=1"
          PHP_IDE_CONFIG: "serverName=Docker"

  php-cli:
    build:
      context: ./php-cli
    volumes:
      - ../:/var/www/instructions
    command: sleep 25000
    container_name: ${COMPOSE_PROJECT_NAME}-cli
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_port=9001 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
